import MuiBackToTopPlugin from './back-to-top';
import MuiButtonPlugin from './button';
import MuiCardPlugin from './card';
import MuiCheckboxPlugin from './checkbox';
import MuiDatePickerPlugin from './date-picker';
import MuiDialogPlugin from './dialog';
import MuiDrawerPlugin from './drawer';
import MuiExpanderPlugin from './expander';
import MuiFormsPlugin from './forms';
import MuiFileDropperPlugin from './file-dropper';
import MuiFocusTrapPlugin from './focus-trap';
import MuiIconPlugin from './icon';
import MuiListPlugin from './list';
import MuiMenuPlugin from './menu';
import MuiNavPlugin from './nav';
import MuiPaginatorPlugin from './paginator';
import MuiPopperPlugin from './popper';
import MuiProgressBarPlugin from './progress-bar';
import MuiProgressSpinnerPlugin from './progress-spinner';
import MuiRadioPlugin from './radio';
import MuiSliderPlugin from './slider';
import MuiSlushBucketPlugin from './slush-bucket';
import MuiSwitchPlugin from './switch';
import MuiTablePlugin from './table';
import MuiTabsPlugin from './tabs';
import MuiTimePickerPlugin from './time-picker';
import MuiToastPlugin from './toast';
import MuiTogglePlugin from './toggle';
import MuiToolbarPlugin from './toolbar';
import MuiTooltipPlugin from './tooltip';
import MuiWysiwygPlugin from './wysiwyg';

export default Vue => {
  Vue.use(MuiBackToTopPlugin);
  Vue.use(MuiButtonPlugin);
  Vue.use(MuiCardPlugin);
  Vue.use(MuiCheckboxPlugin);
  Vue.use(MuiDatePickerPlugin);
  Vue.use(MuiDialogPlugin);
  Vue.use(MuiDrawerPlugin);
  Vue.use(MuiExpanderPlugin);
  Vue.use(MuiFormsPlugin);
  Vue.use(MuiFileDropperPlugin);
  Vue.use(MuiFocusTrapPlugin);
  Vue.use(MuiIconPlugin);
  Vue.use(MuiListPlugin);
  Vue.use(MuiMenuPlugin);
  Vue.use(MuiNavPlugin);
  Vue.use(MuiPaginatorPlugin);
  Vue.use(MuiPopperPlugin);
  Vue.use(MuiProgressBarPlugin);
  Vue.use(MuiProgressSpinnerPlugin);
  Vue.use(MuiRadioPlugin);
  Vue.use(MuiSliderPlugin);
  Vue.use(MuiSlushBucketPlugin);
  Vue.use(MuiSwitchPlugin);
  Vue.use(MuiTablePlugin);
  Vue.use(MuiTabsPlugin);
  Vue.use(MuiTimePickerPlugin);
  Vue.use(MuiToastPlugin);
  Vue.use(MuiTogglePlugin);
  Vue.use(MuiToolbarPlugin);
  Vue.use(MuiTooltipPlugin);
  Vue.use(MuiWysiwygPlugin);
};
